import { pgTable, text, timestamp, integer, boolean, json, uuid, varchar, pgEnum } from 'drizzle-orm/pg-core';
import { createId } from '@paralleldrive/cuid2';

// Enums
export const subscriptionPlanEnum = pgEnum('subscription_plan', ['free', 'pro']);
export const subscriptionStatusEnum = pgEnum('subscription_status', ['active', 'expired', 'cancelled']);
export const documentStatusEnum = pgEnum('document_status', ['uploading', 'processing', 'ready', 'error']);
export const messageRoleEnum = pgEnum('message_role', ['user', 'assistant', 'system']);

// Users table
export const users = pgTable('users', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  clerkId: varchar('clerk_id', { length: 255 }).notNull().unique(),
  email: varchar('email', { length: 255 }).notNull(),
  firstName: varchar('first_name', { length: 255 }),
  lastName: varchar('last_name', { length: 255 }),
  
  // Subscription details
  subscriptionPlan: subscriptionPlanEnum('subscription_plan').notNull().default('free'),
  subscriptionStatus: subscriptionStatusEnum('subscription_status').notNull().default('active'),
  subscriptionStartDate: timestamp('subscription_start_date').defaultNow(),
  subscriptionEndDate: timestamp('subscription_end_date'),
  stripeCustomerId: varchar('stripe_customer_id', { length: 255 }),
  stripeSubscriptionId: varchar('stripe_subscription_id', { length: 255 }),
  
  // Usage tracking
  documentsUploaded: integer('documents_uploaded').notNull().default(0),
  messagesUsed: integer('messages_used').notNull().default(0),
  lastResetDate: timestamp('last_reset_date').defaultNow(),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Documents table
export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sessionId: varchar('session_id', { length: 255 }).notNull(),
  
  name: varchar('name', { length: 500 }).notNull(),
  content: text('content'),
  
  // File metadata
  fileType: varchar('file_type', { length: 100 }),
  fileSize: integer('file_size'),
  sourceUrl: text('source_url'),
  
  // Processing status
  status: documentStatusEnum('status').notNull().default('uploading'),
  
  // Vector database references
  qdrantCollectionId: varchar('qdrant_collection_id', { length: 255 }),
  chunksCount: integer('chunks_count').default(0),
  
  // Additional metadata
  metadata: json('metadata'),
  
  // Timestamps
  uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
  processedAt: timestamp('processed_at'),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Chat conversations table
export const conversations = pgTable('conversations', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sessionId: varchar('session_id', { length: 255 }).notNull(),
  
  title: varchar('title', { length: 500 }),
  summary: text('summary'),
  
  // Conversation metadata
  documentIds: json('document_ids').$type<string[]>().default([]),
  totalMessages: integer('total_messages').default(0),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Chat messages table
export const messages = pgTable('messages', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  conversationId: uuid('conversation_id').notNull().references(() => conversations.id, { onDelete: 'cascade' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  
  role: messageRoleEnum('role').notNull(),
  content: text('content').notNull(),
  
  // Message metadata
  tokenCount: integer('token_count'),
  model: varchar('model', { length: 100 }),
  citations: json('citations'),
  metadata: json('metadata'),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Notes table
export const notes = pgTable('notes', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sessionId: varchar('session_id', { length: 255 }).notNull(),
  
  title: varchar('title', { length: 500 }).notNull(),
  content: text('content').notNull(),
  
  // Note metadata
  documentIds: json('document_ids').$type<string[]>().default([]),
  tags: json('tags').$type<string[]>().default([]),
  isAutoGenerated: boolean('is_auto_generated').default(false),
  
  // Processing info
  model: varchar('model', { length: 100 }),
  tokenCount: integer('token_count'),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// User sessions table (for tracking user activity)
export const userSessions = pgTable('user_sessions', {
  id: uuid('id').primaryKey().$defaultFn(() => createId()),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sessionId: varchar('session_id', { length: 255 }).notNull().unique(),
  
  // Session metadata
  ipAddress: varchar('ip_address', { length: 45 }),
  userAgent: text('user_agent'),
  lastActivity: timestamp('last_activity').defaultNow().notNull(),
  
  // Session data
  documentCount: integer('document_count').default(0),
  messageCount: integer('message_count').default(0),
  noteCount: integer('note_count').default(0),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Export types
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Document = typeof documents.$inferSelect;
export type NewDocument = typeof documents.$inferInsert;
export type Conversation = typeof conversations.$inferSelect;
export type NewConversation = typeof conversations.$inferInsert;
export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;
export type Note = typeof notes.$inferSelect;
export type NewNote = typeof notes.$inferInsert;
export type UserSession = typeof userSessions.$inferSelect;
export type NewUserSession = typeof userSessions.$inferInsert;